build: off

environment:
  matrix:
    - job_name: ubuntu
      appveyor_build_worker_image: Ubuntu2004
      APPVEYOR: True
      CI: True
    - job_name: macos
      appveyor_build_worker_image: macos
      APPVEYOR: True
      CI: True
    - job_name: windows
      appveyor_build_worker_image: Visual Studio 2019
      CHERE_INVOKING: 1
      MSYSTEM: MINGW64
      RUBY_VERSION: 27

for:
  -
    matrix:
      only:
        - job_name: ubuntu
    test_script:
      - sh: scripts/ci_test.sh

  -
    matrix:
      only:
        - job_name: macos
    test_script:
      - sh: sudo -E scripts/ci_test.sh

  -
    matrix:
      only:
        - job_name: windows
    init:
      - cmd: set PATH="C:\Ruby%RUBY_VERSION%\bin;%PATH%"
    test_script:
      - cmd: C:\msys64\usr\bin\bash -l "%cd%\scripts\ci_test.sh"
