build: off

environment:
  matrix:
    - job_name: Ubuntu
      appveyor_build_worker_image: Ubuntu2004
    - job_name: MacOS
      appveyor_build_worker_image: macos
    - job_name: Windows
      appveyor_build_worker_image: Visual Studio 2019
      CHERE_INVOKING: 1
      MSYSTEM: MINGW64

for:
  -
    matrix:
      only:
        - job_name: Ubuntu
        - job_name: MacOS
    test_script:
      - sh: scripts/ci_test.sh

  # -
  #   matrix:
  #     only:
  #       - job_name: MacOS
  #   test_script:
  #     - sh: scripts/ci_test.sh

  -
    matrix:
      only:
        - job_name: Windows
    test_script:
      - cmd: C:\msys64\usr\bin\bash -cl "./scripts/ci_test.sh"
