language: ruby

matrix:
  include:
    - os: linux
      arch: amd64
      dist: focal
      rvm: 2.5
    - os: linux
      arch: amd64
      dist: focal
      rvm: 2.6
    - os: linux
      arch: amd64
      dist: focal
      rvm: 2.7
    - os: osx
      arch: amd64
      osx_image: xcode12.2
      rvm: 2.5
    - os: osx
      arch: amd64
      osx_image: xcode12.2
      rvm: 2.6
    - os: osx
      arch: amd64
      osx_image: xcode12.2
      rvm: 2.7

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh
