language: ruby

jobs:
  include:
    - os: linux
      arch: amd64
      dist: focal
      rvm: 2.5
    - os: linux
      arch: amd64
      dist: focal
      rvm: 2.6
    - os: linux
      arch: amd64
      dist: focal
      rvm: 2.7
    - os: linux
      arch: arm64
      dist: focal

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh
