language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7

dist: focal
osx_image: xcode12.2

jobs:
  include:
    - os: linux
      arch: amd64
    - os: osx
      arch: amd64

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh
