version: 2.1

orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.0.3

jobs:
  build:
    docker:
      - image: puchuu/test-ocg_x86_64-unknown-linux-gnu:latest
    working_directory: /mnt/data
    steps:
      - git-shallow-clone/checkout
      - run: /home/ci_test.sh

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: circleci
