version: 2

jobs:
  build:
    docker:
      - image: puchuu/test-ocg_i686-gentoo-linux-musl:latest
    steps:
      - run: |
          gem install ocg || true
          gem install --no-user-install ocg || true
          env
          whoami
          /home/ci_test.sh
    filters:
      branches:
        only: circleci
