name: tests

on:
  - push

jobs:
  test:
    runs-on:
      - ubuntu-latest
      - macos-latest
      - windows-latest

    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Rake
        run: bundle exec rake
