name: test

on:
  - push

jobs:
  ubuntu:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: CI test
        run: scripts/ci_test.sh

  macos:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: CI test
        run: scripts/ci_test.sh

  windows:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: CI test
        run: call "C:\Program Files\Git\bin\bash.exe" -l "%cd%\scripts\ci_test.sh"

  windows-mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          install: git mingw-w64-x86_64-ruby
      - name: CI test
        run: C:\msys64\usr\bin\bash.exe -l "%cd%\scripts\ci_test.sh"
        env:
          MSYSTEM: MINGW64

  windows-cygwin:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          install-dir: C:\cygwin64
          packages: git ruby
      - name: CI test
        run: |
          set "PATH="
          C:\cygwin64\bin\bash.exe -l "%cd%\scripts\ci_test.sh"
        env:
          CHERE_INVOKING: 1
          SHELLOPTS: igncr
